<a href="https://colab.research.google.com/github/devdandekar24/DeepLearning/blob/main/perceptron_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Perceptron class ( sigmoid )

In [26]:
class SigmoidPerceptron():
  # to initiate the parameters
  def  __init__(self, input_size):
    self.weights= np.random.randn(input_size)
    self.bias=np.random.randn(1)

  def sigmoid(self,z):
    return 1/(1+np.exp(-z))

  def predict(self, inputs):
    weighted_sum= np.dot(inputs, self.weights) + self.bias
    return self.sigmoid(weighted_sum)

  def fit(self, inputs, targets, learning_rate, num_epochs):
    num_examples= inputs.shape[0]
    for epoch in range(num_epochs):
      # in case of standard gradient descent code will be here
      for i in range(num_examples):

        # code for stoichastic gradient descent is here

        input_vector= inputs[i]
        target=targets[i]
        # output must be zero or one, but not here as we are using sigmoid function
        prediction=self.predict(input_vector)
        error= target-prediction

        # update weights
        gradient_weights= error* prediction* (1-prediction) * input_vector
        self.weights += learning_rate * gradient_weights

        # update bias
        gradient_bias= error* prediction* (1-prediction)
        self.bias += learning_rate * gradient_bias

  def evaluate(self, inputs, targets):
    correct = 0
    for input_vector, target in zip(inputs, targets):
      prediction= self.predict(input_vector)

      if prediction >= 0.5:
        predicted_class =1

      else:
        predicted_class =0

      if predicted_class == target:
        correct +=1

    accuracy= correct/len(inputs)   # accuracy= no. of correct predictions / total no. of datapts
    return accuracy

In [3]:
# list1 = [10, 20, 30]
# list2 = [0.2, 0.3, 0.4]


# for val1,val2 in zip(list1,list2):
#   print(val1, val2)

Importing Dependencies

In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [5]:
df=pd.read_csv("diabetes.csv")

In [6]:
df.shape

(768, 9)

In [7]:
df.head()

   Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [8]:
df['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [9]:
class_o_df=df[df['Outcome']==0]
class_1_df=df[df['Outcome']==1]

class_o_df=class_o_df.sample(268)

data=pd.concat([class_o_df,class_1_df])

In [10]:
data.head()

     Pregnancies  Glucose  ...  Age  Outcome
79             2      112  ...   24        0
643            4       90  ...   31        0
274           13      106  ...   52        0
562            1       87  ...   24        0
713            0      134  ...   21        0

[5 rows x 9 columns]

In [11]:
data.tail()

     Pregnancies  Glucose  ...  Age  Outcome
755            1      128  ...   37        1
757            0      123  ...   52        1
759            6      190  ...   66        1
761            9      170  ...   43        1
766            1      126  ...   47        1

[5 rows x 9 columns]

In [12]:
data.shape

(536, 9)

In [13]:
data['Outcome'].value_counts()

Outcome
0    268
1    268
Name: count, dtype: int64

In [14]:
X= data.drop('Outcome',axis=1)
Y=data['Outcome']

In [15]:
type(X)

pandas.core.frame.DataFrame

In [16]:
X

     Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
79             2      112             66  ...  25.0                     0.307   24
643            4       90              0  ...  28.0                     0.610   31
274           13      106             70  ...  34.2                     0.251   52
562            1       87             68  ...  37.6                     0.401   24
713            0      134             58  ...  26.4                     0.352   21
..           ...      ...            ...  ...   ...                       ...  ...
755            1      128             88  ...  36.5                     1.057   37
757            0      123             72  ...  36.3                     0.258   52
759            6      190             92  ...  35.5                     0.278   66
761            9      170             74  ...  44.0                     0.403   43
766            1      126             60  ...  30.1                     0.349   47

[536 rows x 8 columns]

In [17]:
X=X.values
Y=Y.values

In [18]:
type(X)

numpy.ndarray

In [19]:
X

array([[  2.   , 112.   ,  66.   , ...,  25.   ,   0.307,  24.   ],
       [  4.   ,  90.   ,   0.   , ...,  28.   ,   0.61 ,  31.   ],
       [ 13.   , 106.   ,  70.   , ...,  34.2  ,   0.251,  52.   ],
       ...,
       [  6.   , 190.   ,  92.   , ...,  35.5  ,   0.278,  66.   ],
       [  9.   , 170.   ,  74.   , ...,  44.   ,   0.403,  43.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ]])

In [20]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

Train Test Split

In [32]:
X_train, X_test, Y_train, Y_test= train_test_split(X,Y,test_size=0.2, stratify=Y,random_state=123)

In [33]:
scaler= StandardScaler()
X_train_scale=scaler.fit_transform(X_train)
X_test_scale=scaler.transform(X_test)

In [34]:
 X_train_scale.shape[1]

8

In [35]:
# sigmoid Perceptron

perceptron= SigmoidPerceptron(input_size= X_train_scale.shape[1])

In [36]:
#  train the perceptron model
perceptron.fit(inputs=X_train_scale, targets=Y_train, learning_rate=0.1, num_epochs=100)

Model Evaluation

In [37]:
#  evaluate the model for training data
accuracy= perceptron.evaluate(X_train_scale, Y_train)
accuracy=round(accuracy*100,2)
print('Training Accuracy= ', accuracy,'%')

Training Accuracy=  75.7 %

In [38]:
#  evaluate the model for testing data
accuracy= perceptron.evaluate(X_test_scale, Y_test)
accuracy=round(accuracy*100,2)
print('Testing Accuracy= ', accuracy,'%')

Testing Accuracy=  78.7 %